def test_gather_all_exceptions():
    pass
